moneydero/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

from .views import *

urlpatterns = patterns('',
    # Examples:
    url(r'^$', ResumenView.as_view(), name='home'),
    url(r'^resumen/$', ResumenView.as_view(), name='resumen'),
    url(r'^movimientos/$', MovimientosView.as_view(), name='movimientos'),

    url(r'^login/', LoginView.as_view(), name="login"),
    url(r'^admin/', include(admin.site.urls)),
)

moneydero/models.py
from django.db import models
from django.db.models import Q
from django.contrib.auth.models import User
from django.contrib.postgres.fields import ArrayField


class Perfil(models.Model):
	user = models.OneToOneField(User)

	@property
	def categorias(self):
		return Categoria.objects.filter(cuentas__titulares=self.user)

	@property
	def cuentas(self):
		return Cuenta.objects.filter(titulares=self.user)

	@property
	def movimientos(self):
		return Movimiento.objects.filter(cuenta__titulares=self.user)

	def __str__(self):
		return self.user.username


class Categoria(models.Model):
	nombre = models.CharField(max_length=50)
	padre  = models.ForeignKey('Categoria', null=True, blank=True)
	cuentas = models.ManyToManyField('Cuenta')

	def __str__(self):
		return self.nombre



class Cuenta(models.Model):
	nombre    = models.CharField(max_length=50)
	titulares = models.ManyToManyField(User)

	def __str__(self):
		return self.nombre



class Movimiento(models.Model):
	user              = models.ForeignKey(User, db_index=True)
	fecha             = models.DateTimeField()
	concepto          = models.CharField(max_length=100)
	categoria         = models.ForeignKey(Categoria)
	cuenta            = models.ForeignKey(Cuenta)
	importe           = models.DecimalField(max_digits=12, decimal_places=2)
	saldo             = models.DecimalField(max_digits=12, decimal_places=2, blank=True)

	class Meta:
		ordering = ('fecha', )

	def guarda(self, user):
		anterior = Movimiento.objects.filter(fecha__lt=self.fecha, user=user, cuenta=self.cuenta).order_by('fecha').last()
		if anterior:
			self.saldo = anterior.saldo + self.importe
		else:
			self.saldo = self.importe
		super().save()
		proximo = Movimiento.objects.filter(fecha__gt=self.fecha, user=user, cuenta=self.cuenta).order_by('fecha').first()
		if proximo:
			proximo.guarda(user)

	@property
	def saldo_global(self, user):
		pass

	def __str__(self):
		return self.concepto

moneydero/forms.py
from django import forms

class FormAsiento(forms.Form):
    fecha = forms.DateField()
    cuenta = forms.IntegerField()
    categoria = forms.IntegerField()
    concepto = forms.CharField()
    #signo = forms.BooleanField()
    cantidad = forms.DecimalField(decimal_places=2, max_digits=12)


class FormLogin(forms.Form):
    username = forms.CharField()
    password = forms.CharField()

moneydero/views.py
from django.shortcuts import redirect
from django.views.generic import TemplateView, View, FormView
from django.utils import timezone
from django.contrib.auth import authenticate, login, logout
from .models import *
from .forms import FormAsiento, FormLogin
from datetime import timedelta
from calendar import monthrange

class BaseView(View):
    def dispatch(self, *args, **kwargs):
        if self.request.user.is_authenticated():
                return super().dispatch(*args, **kwargs)
        return redirect('/login/')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['session'] = self.request.session
        return context

    def post(self, request, *args, **kwargs):
        if 'fecha' in request.POST:
            form_class = self.get_form_class()
            form = self.get_form(form_class)
            if form.is_valid():
                return self.form_valid(form, **kwargs)
            else:
                return self.form_invalid(form, **kwargs)
        if 'categoria' in request.POST:
            try:
                request.session['categoria'] = self.request.user.perfil.categorias.get(pk=request.POST['categoria']).nombre
            except:
                request.session['categoria'] = None
        elif 'periodo' in request.POST:
            if request.POST['periodo'] == 'personalizado':
                pass
            else:
                request.session['periodo'] = request.POST['periodo']
        return redirect(request.path)

    def saldo(self):
        if self.request.session.get('categoria', default='0') == '0':
            saldos = []
            for categoria in self.request.user.categorias:
                if self.request.session.get('periodo', default='Siempre') != 'Siempre':
                    saldo = Movimiento.objects.filter(
                                                perfil=self.request.user.perfil,
                                                categoria=categoria
                                                ).last().saldo
                else:
                    saldo = Movimiento.objects.filter(
                                                perfil=self.request.user.perfil,
                                                categoria=categoria,
                                                fecha__lte=self.fin()
                                                ).last().saldo

    def fin(self):
        periodo = self.request.get('periodo', default="Siempre")
        ahora = timezone.now()
        if periodo == 'Siempre':
            return None
        elif periodo == 'Hoy':
            return ahora.replace(hour=23, minute=59, second=59)
        elif periodo == 'Esta semana':
            faltan = 6 - ahora.weekday()
            return (ahora + timedelta(days=faltan)).replace(hour=23, minute=59, second=59)
        elif periodo == 'Este mes':
            fin = monthrange(ahora.year, ahora.month)[1]
            return ahora.replace(day=fin, hour=23, minute=59, second=59)
        elif periodo == 'Este año':
            return ahora.replace(month=12, day=31, hour=23, minute=59, second=59)
        elif periodo == 'personalizado':
            return None
        return ahora



class ResumenView(BaseView, TemplateView):
    template_name = 'moneydero/resumen.html'



class MovimientosView(BaseView, FormView):
    template_name = 'moneydero/movimientos.html'
    form_class = FormAsiento
    success_url = '/movimientos/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.session.get('categoria', None):
            context['movimientos'] = self.request.user.perfil.movimientos.filter(categoria__nombre=self.request.session['categoria']).order_by('-fecha')
        else:
            context['movimientos'] = self.request.user.perfil.movimientos.order_by('-fecha')
        return context

    def form_valid(self, form):
        if 'signo' in self.request.POST:
            importe = form.cleaned_data['cantidad']
        else:
            importe = -form.cleaned_data['cantidad']
        categoria=Categoria.objects.get(pk=form.cleaned_data['categoria'])
        cuenta=Cuenta.objects.get(pk=form.cleaned_data['cuenta'], titulares=self.request.user)
        ok = Categoria.objects.filter(cuentas=cuenta).exists()
        if ok:
            movimiento = Movimiento(user=self.request.user,
                                    fecha=form.cleaned_data['fecha'],
                                    concepto=form.cleaned_data['concepto'],
                                    categoria=categoria,
                                    cuenta=cuenta,
                                    importe=importe,
            )
            movimiento.guarda(user=self.request.user)
        return super().form_valid(form)


class LoginView(FormView):
    template_name = 'moneydero/login.html'
    form_class = FormLogin
    success_url = '/'

    def form_valid(self, form):
        usuario = authenticate(username=form.cleaned_data['username'], password=form.cleaned_data['password'])
        if usuario is not None:
            if usuario.is_active:
                login(self.request, usuario)
        return super().form_valid(form)

moneydero/templates/moneydero/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Moneydero</title>
    <link href="{% static 'moneydero/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'moneydero/css/bootstrap-toggle.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="http://code.jquery.com/ui/1.10.1/themes/base/jquery-ui.css" />
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="{% static 'moneydero/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'moneydero/js/bootstrap-toggle.min.js' %}"></script>
</head>
<body>
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">Moneydero</a>
            </div>

            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li class="dropdown">
                        <form method="POST" id="form_categoria">{% csrf_token %}
                            <input type="hidden" name="categoria" id="field_categoria">
                        </form>
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{ session.categoria | default:"Todas las categorías" }} <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>
                                <a href="javascript:;" onClick="document.getElementById('field_categoria').value='0'; document.getElementById('form_categoria').submit();">Todas las categorías</a>
                            </li>
                            <li role="separator" class="divider"></li>
                            {% for categoria in user.perfil.categorias %}
                                <li>
                                    <form method="POST" id="Categoria{{ categoria.pk }}">{% csrf_token %}
                                        <input type="hidden" name="categoria" value="{{ categoria.pk }}">
                                    </form>
                                    <a href="javascript:;" onClick="document.getElementById('field_categoria').value='{{ categoria.pk }}'; document.getElementById('form_categoria').submit();">{{ categoria }}</a>
                                </li>
                            {% endfor %}
                        </ul>
                    </li>
                    <li class="dropdown">
                        <form method="POST" id="form_periodo">{% csrf_token %}
                            <input type="hidden" name="periodo" id="field_periodo">
                            <input type="hidden" name="desde" id="field_desde">
                            <input type="hidden" name="hasta" id="field_hasta">
                        </form>
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{ session.periodo | default:"Siempre" }} <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="javascript:;" onClick="document.getElementById('field_periodo').value='Siempre'; document.getElementById('form_periodo').submit();">Siempre</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="javascript:;" onClick="document.getElementById('field_periodo').value='Hoy'; document.getElementById('form_periodo').submit();">Hoy</a></li>
                            <li><a href="javascript:;" onClick="document.getElementById('field_periodo').value='Esta semana'; document.getElementById('form_periodo').submit();">Esta semana</a></li>
                            <li><a href="javascript:;" onClick="document.getElementById('field_periodo').value='Este mes'; document.getElementById('form_periodo').submit();">Este mes</a></li>
                            <li><a href="javascript:;" onClick="document.getElementById('field_periodo').value='Este año'; document.getElementById('form_periodo').submit();">Este año</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="javascript:;" onClick="document.getElementById('field_periodo').value='Últimas 24 horas'; document.getElementById('form_periodo').submit();">Útimas 24 horas</a></li>
                            <li><a href="javascript:;" onClick="document.getElementById('field_periodo').value='Última semana'; document.getElementById('form_periodo').submit();">Última semana</a></li>
                            <li><a href="javascript:;" onClick="document.getElementById('field_periodo').value='Último mes'; document.getElementById('form_periodo').submit();">Últimos mes</a></li>
                            <li><a href="javascript:;" onClick="document.getElementById('field_periodo').value='Último año'; document.getElementById('form_periodo').submit();">Último año</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="javascript:;" onClick="document.getElementById('field_periodo').value='personalizado'; document.getElementById('form_periodo').submit();">Intervalo personalizado</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Todas las cuentas <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="#">Todas las cuentas</a></li>
                        </ul>
                    </li>
                </ul>
                <form class="navbar-form navbar-left" role="search">
                    <div class="form-group">
                        <input type="text" class="form-control" placeholder="Concepto" id="id_filtro_concepto">
                    </div>
                </form>
                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"><span class="glyphicon glyphicon-cog"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="#">Categorias</a></li>
                            <li><a href="#">Cuentas</a></li>
                        </ul>
                    </li>
                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-2">
                <ul class="nav nav-pills nav-stacked">
                    <li role="presentation"{% block resumen %}{% endblock %}><a href="/resumen/">Resumen</a></li>
                    <li role="presentation"{% block movimientos %}{% endblock %}><a href="/movimientos/">Movimientos</a></li>
                </ul>
            </div>
            <div class="col-sm-10 main">
                {% block contenido %}
                {% endblock %}
            </div>
        </div>
    </div>
</body>
</html>

moneydero/templates/moneydero/login.html
{% extends 'moneydero/base.html' %}{% load staticfiles %}
{% block contenido %}
<form class="form-inline" method="POST">{% csrf_token %}
  <div class="form-group">
    <label for="id_username">Usuario</label>
    <input type="text" class="form-control" id="id_username" name="username">
  </div>
  <div class="form-group">
    <label for="id_password">Contraseña</label>
    <input type="password" class="form-control" id="id_password" name="password">
  </div>
  <button type="submit" class="btn btn-default">Entrar</button>
</form>
{% endblock %}

moneydero/templates/moneydero/movimientos.html
{% extends 'moneydero/base.html' %}{% load staticfiles %}
{% block movimientos %} class="active"{% endblock %}
{% block contenido %}
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs1">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
        <li><a href="#" data-toggle="modal" data-target="#modalPlus"><span class="glyphicon glyphicon-plus"></span></a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<table class="table table-hover">
    <tr>
        <th>Fecha</th>
        <th>Importe</th>
        <th>Concepto</th>
        <th>Categoría</th>
        <th>Cuenta</th>
        <th>Saldo</th>
    </tr>
    {% for movimiento in movimientos %}
    <tr>
        <td>{{ movimiento.fecha.date }}</td>
        <td{% if movimiento.importe < 0 %} class="text-danger"{% endif %}>{{ movimiento.importe }}</td>
        <td>{{ movimiento.concepto }}</td>
        <td>{{ movimiento.categoria }}</td>
        <td>{{ movimiento.cuenta }}</td>
        <td{% if movimiento.importe < 0 %} class="text-danger"{% endif %}>{{ movimiento.saldo }}</td>
    </tr>
    {% endfor %}
</table>
<div class="modal fade" id="modalPlus">
    <div class="modal-dialog">
        <div class="modal-content">
            <form method="POST" id="form_asiento">{% csrf_token %}
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title">Insertar movimiento</h4>
                </div>
                <div class="modal-body">
                    {{ form.non_field_errors }}
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="id_fecha">Fecha</label>
                                {{ form.fecha.errors }}
                                <input type="text" id="id_fecha" name="fecha" class="form-control" value="{% now "d/m/Y" %}">
                            </div>
                            <div class="form-group">
                                <label for="id_cuenta">Cuenta</label>
                                {{ form.cuenta.errors }}
                                <select id="id_cuenta" name="cuenta" class="form-control">
                                    {% for cuenta in user.perfil.cuentas %}
                                        <option value="{{ cuenta.pk }}">{{ cuenta }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="id_categoria">Categoría</label>
                                {{ form.categoria.errors }}
                                <select id="id_categoria" name="categoria" class="form-control">
                                    {% for categoria in user.perfil.categorias %}
                                        <option value="{{ categoria.pk }}">{{ categoria}}</option>
                                    {% endfor %}
                                </select>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="id_concepto">Concepto</label>
                                {{ form.concepto.errors }}
                                <textarea name="concepto" id="id_concepto" class="form-control"></textarea>
                            </div>
                            <div class="form-group">
                                <label for="id_cantidad">Cantidad</label>
                                {{ form.cantidad.errors }}
                                <div class="row">
                                    <div class="col-xs-3">
                                        <input data-toggle="toggle" type="checkbox" data-on="+" data-off="-" name="signo">
                                    </div>
                                    <div class="col-xs-9">
                                        <div class="input-group">
                                            <input type="number" step="0.01" min="0" class="form-control" id="id_cantidad" name="cantidad">
                                            <div class="input-group-addon">€</div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                    <button type="submit" class="btn btn-primary">Guardar movimiento</button>
                </div>
            </form>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<script src="//code.jquery.com/ui/1.11.3/jquery-ui.js"></script>
<script>
$(function() {
    $.datepicker.regional['es'] = {
        closeText: 'Cerrar',
        prevText: '<Ant',
        nextText: 'Sig>',
        currentText: 'Hoy',
        monthNames: ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'],
        monthNamesShort: ['Ene','Feb','Mar','Abr', 'May','Jun','Jul','Ago','Sep', 'Oct','Nov','Dic'],
        dayNames: ['Domingo', 'Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado'],
        dayNamesShort: ['Dom','Lun','Mar','Mié','Juv','Vie','Sáb'],
        dayNamesMin: ['Do','Lu','Ma','Mi','Ju','Vi','Sá'],
        weekHeader: 'Sm',
        dateFormat: 'dd/mm/yy',
        firstDay: 1,
        isRTL: false,
        showMonthAfterYear: false,
        yearSuffix: ''
    };
    $.datepicker.setDefaults($.datepicker.regional['es']);
    $( "#id_fecha" ).datepicker({ dateFormat: 'dd/mm/yy' });
});

$('#modalPlus').on('hidden.bs.modal', function (e) {
    $("#form_asiento")[0].reset();
})
</script>
{% endblock %}

moneydero/templates/moneydero/resumen.html
{% extends 'moneydero/base.html' %}{% load staticfiles %}
{% block resumen %} class="active"{% endblock %}
{% block contenido %}
<div class="row">
    <div class="col-sm-6 col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Saldo</h3>
            </div>
            <div class="panel-body">
                <div class="list-group">
                    {% for categoria in categorias %}
                        <li class="list-group-item">
                            {{ categoria }}<span class="badge">{{ categoria.saldo }}</span>
                        </li>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}